# sonic-cfg-schema package

SONIC_CFG_SCHEMA = sonic_cfg_schema-1.0.0-py3-none-any.whl
$(SONIC_CFG_SCHEMA)_SRC_PATH = $(SRC_PATH)/sonic-cfg-schema
$(SONIC_CFG_SCHEMA)_PYTHON_VERSION = 3
$(SONIC_CFG_SCHEMA)_DEBS_DEPENDS = $(LIBYANG) $(LIBYANG_CPP) $(LIBYANG_PY3)
$(SONIC_CFG_SCHEMA)_DEPENDS =  $(SONIC_YANG_MGMT_PY3) $(SONIC_YANG_MODELS_PY3)
$(SONIC_CFG_SCHEMA)_RDEPENDS = $(SONIC_YANG_MGMT_PY3) $(SONIC_YANG_MODELS_PY3) $(LIBYANG) \
                                 $(LIBYANG_CPP) $(LIBYANG_PY3)

SONIC_PYTHON_WHEELS += $(SONIC_CFG_SCHEMA)